# src/core/schemas.py
from dataclasses import dataclass
from datetime import datetime
from typing import Optional, Dict, Any

# ---------------------------
# Market data schemas
# ---------------------------

@dataclass
class Tick:
    """
    A single trade/tick (best used for very-high-frequency data).
    Fields:
      - timestamp: datetime of the tick (UTC)
      - symbol: instrument identifier (e.g. 'BTCUSDT', 'RELIANCE')
      - price: trade price or last price
      - size: trade size/quantity (may be None)
      - bid: best bid (optional)
      - ask: best ask (optional)
      - meta: optional dict for adapter-specific raw info
    """
    timestamp: datetime
    symbol: str
    price: float
    size: Optional[float] = None
    bid: Optional[float] = None
    ask: Optional[float] = None
    meta: Optional[Dict[str, Any]] = None


@dataclass
class Bar:
    """
    An OHLCV bar/candle aggregated over a timeframe (e.g. 1m, 1h).
    Fields:
      - timestamp: bar close time (datetime, UTC)
      - symbol: instrument id
      - open/high/low/close: float
      - volume: float
      - timeframe: string label like '1m','15m','1h'
      - meta: optional dict for adapter-specific raw info
    """
    timestamp: datetime
    symbol: str
    open: float
    high: float
    low: float
    close: float
    volume: float
    timeframe: str = "1m"
    meta: Optional[Dict[str, Any]] = None


# ---------------------------
# Event wrappers used across engine
# ---------------------------

@dataclass
class MarketSnapshot:
    """
    A synchronized snapshot across multiple symbols/timeframes.
    Example usage: {'timestamp':..., 'binance': {...}, 'zerodha': {...}}
    We store a generic payload so adapters/strategies can read what they need.
    """
    timestamp: datetime
    payload: Dict[str, Any]   # adapter/source -> symbol_tf -> data (Bar/Tick dicts)
    meta: Optional[Dict[str, Any]] = None

@dataclass
class SimpleSnapshot:
    """
    Simple per-symbol snapshot used in BACKTEST mode.
    Matches HistoricalReplayer → strategies → portfolio input.
    """
    timestamp: datetime
    symbol: str
    bid: float
    ask: float
    last: float
    volume: float
    meta: Optional[Dict[str, Any]] = None


@dataclass
class Order:
    """
    Order structure (generated by portfolio from signals).
    - order_id is optional; in backtest it can be None until execution.
    """
    symbol: str
    quantity: float
    direction: str  # 'BUY' or 'SELL'
    order_type: str = "MKT"  # 'MKT' or 'LMT'
    price: Optional[float] = None  # used for limit orders
    order_id: Optional[str] = None
    meta: Optional[Dict[str, Any]] = None


@dataclass
class Fill:
    """
    Execution/fill information returned by execution layer.
    """
    symbol: str
    quantity: float
    direction: str
    fill_price: float
    timestamp: datetime
    commission: float = 0.0
    order_id: Optional[str] = None
    meta: Optional[Dict[str, Any]] = None
